import { Collector, PriceItem, Recycler, Transaction, WasteLot } from './types';

export const INITIAL_COLLECTOR: Collector = {
  collector_id: 'KC-DEL-2026-4892',
  name: 'Ramesh Kumar',
  phone: '+91 98765 43210',
  location: 'Mayapuri E-Waste Belt, Delhi',
  preferred_language: 'हिंदी',
  vehicle_type: 'Electric Cargo Cart (DL-1EC-2309)',
  verified_badge: true,
  member_since: '2026',
  stats: {
    lots_listed: 28,
    lots_completed: 21,
    total_earnings: 42850,
    total_weight_kg: 840,
  },
};

export const INITIAL_LOTS: WasteLot[] = [
  {
    lot_id: 'LOT-2026-104',
    collector_id: 'KC-DEL-2026-4892',
    material: 'Mobile Phone & Tablet PCBs',
    weight_kg: 8.5,
    condition: 'clean',
    description: '42 smartphones dismantled, lithium batteries removed separately',
    location: 'Mayapuri Industrial Area Phase-II',
    estimated_min_value: 6800,
    estimated_max_value: 7650,
    quoted_price: 7225,
    final_price: undefined,
    recycler_id: 'REC-02',
    recycler_name: 'GreenCircle Refurbishers Pvt Ltd',
    status: 'pending',
    created_at: 'Today, 11:30 AM',
    // Compatibility fields
    id: 'LOT-2026-104',
    category: 'Mobile Phone & Tablet PCBs',
    weightKg: 8.5,
    estimatedPrice: 7225,
    createdAt: 'Today, 11:30 AM',
    recyclerName: 'GreenCircle Refurbishers Pvt Ltd',
    itemsSummary: '42 smartphones dismantled, motherboards with gold contact pins',
  },
  {
    lot_id: 'LOT-2026-103',
    collector_id: 'KC-DEL-2026-4892',
    material: 'Stripped Copper Wire Scrap',
    weight_kg: 14.0,
    condition: 'clean',
    description: 'Grade-A clean stripped copper wire from industrial motors',
    location: 'Naraina Iron & Scrap Mandi',
    estimated_min_value: 6400,
    estimated_max_value: 7000,
    quoted_price: 6720,
    final_price: 6720,
    recycler_id: 'REC-01',
    recycler_name: 'EcoTech E-Waste Recyclers',
    status: 'in_transit',
    created_at: 'Today, 09:15 AM',
    // Compatibility fields
    id: 'LOT-2026-103',
    category: 'Stripped Copper Wire Scrap',
    weightKg: 14.0,
    estimatedPrice: 6720,
    createdAt: 'Today, 09:15 AM',
    recyclerName: 'EcoTech E-Waste Recyclers',
    itemsSummary: 'Grade-A clean stripped copper wire from motors and cords',
  },
  {
    lot_id: 'LOT-2026-102',
    collector_id: 'KC-DEL-2026-4892',
    material: 'Computer Motherboards & RAM',
    weight_kg: 12.0,
    condition: 'mixed',
    description: 'Server & desktop boards, heat-sinks detached, RAM pins intact',
    location: 'Okhla Industrial Shed 4',
    estimated_min_value: 9600,
    estimated_max_value: 10800,
    quoted_price: 10200,
    final_price: 10200,
    recycler_id: 'REC-01',
    recycler_name: 'EcoTech E-Waste Recyclers',
    status: 'accepted',
    created_at: 'Yesterday',
    // Compatibility fields
    id: 'LOT-2026-102',
    category: 'Computer Motherboards & RAM',
    weightKg: 12.0,
    estimatedPrice: 10200,
    createdAt: 'Yesterday',
    recyclerName: 'EcoTech E-Waste Recyclers',
    itemsSummary: 'Server and desktop circuit boards with gold-plated pins',
  },
  {
    lot_id: 'LOT-2026-101',
    collector_id: 'KC-DEL-2026-4892',
    material: 'Lithium-Ion Battery Packs',
    weight_kg: 6.2,
    condition: 'damaged',
    description: 'Laptop 18650 packs with terminal tapes for fire safety',
    location: 'Mayapuri Belt Gate 2',
    estimated_min_value: 900,
    estimated_max_value: 1100,
    quoted_price: 990,
    final_price: 990,
    recycler_id: 'REC-03',
    recycler_name: 'Mayapuri Authorized Smelting Hub',
    status: 'completed',
    created_at: '8 Sep 2026',
    // Compatibility fields
    id: 'LOT-2026-101',
    category: 'Lithium-Ion Battery Packs',
    weightKg: 6.2,
    estimatedPrice: 990,
    createdAt: '8 Sep 2026',
    recyclerName: 'Mayapuri Authorized Smelting Hub',
    itemsSummary: 'Laptop batteries, tape-insulated terminals for fire safety',
  },
];

export const NEARBY_RECYCLERS: Recycler[] = [
  {
    recycler_id: 'REC-01',
    organization_name: 'EcoTech E-Waste Recyclers',
    location: 'Plot 42, Phase-II, Mayapuri Industrial Area, New Delhi',
    distance_km: 1.8,
    materials_accepted: ['PCB', 'Motherboards', 'Cables', 'Copper Wire', 'Motors / Magnets'],
    authorization_number: 'CPCB/EW/DL/2024/098',
    authorization_status: 'authorized',
    offered_rates: {
      pcb: 540,
      cables: 690,
      motors: 260,
      lcd: 220,
    },
    pickup_available: true,
    service_area: 'West Delhi, Central Delhi (Within 15 km)',
    rating: 4.8,
    // Compatibility
    id: 'REC-01',
    name: 'EcoTech E-Waste Recyclers',
    cpcbRegNumber: 'CPCB/EW/DL/2024/098',
    distanceKm: 1.8,
    acceptedMaterials: ['Motherboards', 'Copper Cables', 'Laptop Scrap', 'Motors'],
    address: 'Plot 42, Phase-II, Mayapuri Industrial Area',
    isVerified: true,
  },
  {
    recycler_id: 'REC-02',
    organization_name: 'GreenCircle Refurbishers Pvt Ltd',
    location: 'Shed 12, Okhla Industrial Phase-1, New Delhi',
    distance_km: 3.2,
    materials_accepted: ['PCB', 'LCD / LED', 'Batteries', 'Smartphones', 'Cables'],
    authorization_number: 'CPCB/EW/DL/2023/412',
    authorization_status: 'authorized',
    offered_rates: {
      pcb: 555,
      lcd: 240,
      batteries: 175,
      cables: 660,
    },
    pickup_available: true,
    service_area: 'South Delhi, Noida Border (Within 25 km)',
    rating: 4.7,
    // Compatibility
    id: 'REC-02',
    name: 'GreenCircle Refurbishers Pvt Ltd',
    cpcbRegNumber: 'CPCB/EW/DL/2023/412',
    distanceKm: 3.2,
    acceptedMaterials: ['Smartphones', 'PCBs', 'Li-Ion Batteries', 'LCD Screens'],
    address: 'Shed 12, Okhla Industrial Phase-1',
    isVerified: true,
  },
  {
    recycler_id: 'REC-03',
    organization_name: 'Delhi Safe-Recycle Metals Hub',
    location: 'G-88, Naraina Industrial Complex, New Delhi',
    distance_km: 4.5,
    materials_accepted: ['CRT', 'Motors / Magnets', 'Mixed Plastics', 'Batteries', 'Other E-Waste'],
    authorization_number: 'CPCB/EW/DL/2025/781',
    authorization_status: 'authorized',
    offered_rates: {
      crt: 65,
      motors: 270,
      plastics: 45,
      batteries: 155,
      other: 75,
    },
    pickup_available: false,
    service_area: 'Naraina, Mayapuri, Kirti Nagar',
    rating: 4.9,
    // Compatibility
    id: 'REC-03',
    name: 'Delhi Safe-Recycle Metals Hub',
    cpcbRegNumber: 'CPCB/EW/DL/2025/781',
    distanceKm: 4.5,
    acceptedMaterials: ['Cathode Ray Tubes', 'SMPS', 'Mixed Appliances', 'CRT Glass'],
    address: 'G-88, Naraina Industrial Complex',
    isVerified: true,
  },
  {
    recycler_id: 'REC-04',
    organization_name: 'Bharat Green Resource Extraction LLP',
    location: 'Sector 58, Faridabad Eco-Zone',
    distance_km: 7.8,
    materials_accepted: ['PCB', 'Cables', 'Batteries', 'Motors / Magnets'],
    authorization_number: 'CPCB/EW/HR/2025/119',
    authorization_status: 'authorized',
    offered_rates: {
      pcb: 560,
      cables: 705,
      batteries: 170,
    },
    pickup_available: true,
    service_area: 'NCR South & East Region',
    rating: 4.6,
    // Compatibility
    id: 'REC-04',
    name: 'Bharat Green Resource Extraction LLP',
    cpcbRegNumber: 'CPCB/EW/HR/2025/119',
    distanceKm: 7.8,
    acceptedMaterials: ['Printed Circuit Boards', 'Industrial Cables', 'Lithium Cells'],
    address: 'Sector 58, Faridabad Eco-Zone',
    isVerified: true,
  },
];

export const DAILY_PRICE_BOARD: PriceItem[] = [
  {
    id: 'PRC-01',
    material: 'PCB',
    location: 'Delhi-NCR (Benchmark)',
    market_min: 480,
    market_max: 560,
    unit: 'kg',
    trend: 'up',
    change_amount: 30,
    updated_at: 'Today, 10:30 AM',
    min_grading: 'Complete circuit boards with chips & ICs intact',
    historical_rates: [
      { day: 'Mon', rate: 505 },
      { day: 'Tue', rate: 510 },
      { day: 'Wed', rate: 520 },
      { day: 'Thu', rate: 525 },
      { day: 'Fri', rate: 540 },
      { day: 'Sat', rate: 550 },
      { day: 'Today', rate: 560 },
    ],
    // Compatibility
    category: 'PCB (Mobile / Server Circuit Boards)',
    currentRate: 540,
    changeAmount: 30,
    minGrading: 'Complete circuit boards with chips & ICs intact',
  },
  {
    id: 'PRC-02',
    material: 'Cables',
    location: 'Delhi-NCR (Benchmark)',
    market_min: 620,
    market_max: 710,
    unit: 'kg',
    trend: 'up',
    change_amount: 25,
    updated_at: 'Today, 10:30 AM',
    min_grading: 'Stripped bright copper wire, 99% pure',
    historical_rates: [
      { day: 'Mon', rate: 640 },
      { day: 'Tue', rate: 655 },
      { day: 'Wed', rate: 660 },
      { day: 'Thu', rate: 670 },
      { day: 'Fri', rate: 685 },
      { day: 'Sat', rate: 690 },
      { day: 'Today', rate: 705 },
    ],
    // Compatibility
    category: 'Cables (Stripped Copper Wires)',
    currentRate: 680,
    changeAmount: 25,
    minGrading: 'Stripped bright copper wire, 99% pure',
  },
  {
    id: 'PRC-03',
    material: 'LCD / LED',
    location: 'Delhi-NCR (Benchmark)',
    market_min: 180,
    market_max: 250,
    unit: 'kg',
    trend: 'stable',
    change_amount: 0,
    updated_at: 'Today, 10:30 AM',
    min_grading: 'Unbroken panels, backlight intact',
    historical_rates: [
      { day: 'Mon', rate: 215 },
      { day: 'Tue', rate: 220 },
      { day: 'Wed', rate: 220 },
      { day: 'Thu', rate: 220 },
      { day: 'Fri', rate: 225 },
      { day: 'Sat', rate: 225 },
      { day: 'Today', rate: 225 },
    ],
    // Compatibility
    category: 'LCD / LED Displays',
    currentRate: 225,
    changeAmount: 0,
    minGrading: 'Unbroken panels, backlight intact',
  },
  {
    id: 'PRC-04',
    material: 'Batteries',
    location: 'Delhi-NCR (Benchmark)',
    market_min: 140,
    market_max: 180,
    unit: 'kg',
    trend: 'down',
    change_amount: 10,
    updated_at: 'Today, 10:30 AM',
    min_grading: 'Non-swollen cylindrical & pouch lithium cells',
    historical_rates: [
      { day: 'Mon', rate: 175 },
      { day: 'Tue', rate: 170 },
      { day: 'Wed', rate: 170 },
      { day: 'Thu', rate: 165 },
      { day: 'Fri', rate: 160 },
      { day: 'Sat', rate: 155 },
      { day: 'Today', rate: 150 },
    ],
    // Compatibility
    category: 'Batteries (Lithium-Ion / Lead Acid)',
    currentRate: 155,
    changeAmount: 10,
    minGrading: 'Non-swollen cylindrical & pouch lithium cells',
  },
  {
    id: 'PRC-05',
    material: 'Motors / Magnets',
    location: 'Delhi-NCR (Benchmark)',
    market_min: 210,
    market_max: 290,
    unit: 'kg',
    trend: 'up',
    change_amount: 15,
    updated_at: 'Today, 10:30 AM',
    min_grading: 'Neodymium magnets & copper windings',
    historical_rates: [
      { day: 'Mon', rate: 235 },
      { day: 'Tue', rate: 240 },
      { day: 'Wed', rate: 250 },
      { day: 'Thu', rate: 255 },
      { day: 'Fri', rate: 260 },
      { day: 'Sat', rate: 270 },
      { day: 'Today', rate: 275 },
    ],
    // Compatibility
    category: 'Motors / Magnets Scrap',
    currentRate: 265,
    changeAmount: 15,
    minGrading: 'Neodymium magnets & copper windings',
  },
  {
    id: 'PRC-06',
    material: 'CRT',
    location: 'Delhi-NCR (Benchmark)',
    market_min: 40,
    market_max: 75,
    unit: 'kg',
    trend: 'stable',
    change_amount: 0,
    updated_at: 'Today, 10:30 AM',
    min_grading: 'Leaded television cathode glass intact',
    historical_rates: [
      { day: 'Mon', rate: 55 },
      { day: 'Tue', rate: 55 },
      { day: 'Wed', rate: 55 },
      { day: 'Thu', rate: 55 },
      { day: 'Fri', rate: 55 },
      { day: 'Sat', rate: 60 },
      { day: 'Today', rate: 60 },
    ],
    // Compatibility
    category: 'CRT Glass Tubes',
    currentRate: 58,
    changeAmount: 0,
    minGrading: 'Leaded television cathode glass intact',
  },
  {
    id: 'PRC-07',
    material: 'Mixed Plastics',
    location: 'Delhi-NCR (Benchmark)',
    market_min: 35,
    market_max: 50,
    unit: 'kg',
    trend: 'stable',
    change_amount: 0,
    updated_at: 'Today, 10:30 AM',
    min_grading: 'Clean sorted ABS/HIPS appliance casings',
    historical_rates: [
      { day: 'Mon', rate: 42 },
      { day: 'Tue', rate: 42 },
      { day: 'Wed', rate: 40 },
      { day: 'Thu', rate: 40 },
      { day: 'Fri', rate: 45 },
      { day: 'Sat', rate: 45 },
      { day: 'Today', rate: 45 },
    ],
    // Compatibility
    category: 'Mixed Plastics (ABS / HIPS)',
    currentRate: 44,
    changeAmount: 0,
    minGrading: 'Clean sorted ABS/HIPS appliance casings',
  },
  {
    id: 'PRC-08',
    material: 'Other E-Waste',
    location: 'Delhi-NCR (Benchmark)',
    market_min: 55,
    market_max: 90,
    unit: 'kg',
    trend: 'up',
    change_amount: 5,
    updated_at: 'Today, 10:30 AM',
    min_grading: 'Mixed peripheral & adapter components',
    historical_rates: [
      { day: 'Mon', rate: 65 },
      { day: 'Tue', rate: 65 },
      { day: 'Wed', rate: 70 },
      { day: 'Thu', rate: 70 },
      { day: 'Fri', rate: 75 },
      { day: 'Sat', rate: 75 },
      { day: 'Today', rate: 80 },
    ],
    // Compatibility
    category: 'Other E-Waste (Mixed Peripherals)',
    currentRate: 72,
    changeAmount: 5,
    minGrading: 'Mixed peripheral & adapter components',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    transaction_id: 'TXN-2026-981',
    lot_id: 'LOT-2026-101',
    collector_id: 'KC-DEL-2026-4892',
    recycler_id: 'REC-03',
    recycler_name: 'Mayapuri Authorized Smelting Hub',
    material: 'Lithium-Ion Battery Packs',
    amount: 990,
    payment_status: 'Paid',
    payment_method: 'Direct Bank / UPI',
    transaction_date: '08 Sep 2026, 04:30 PM',
    receipt_ref: 'CPCB-RCP-8842',
  },
  {
    transaction_id: 'TXN-2026-980',
    lot_id: 'LOT-2026-102',
    collector_id: 'KC-DEL-2026-4892',
    recycler_id: 'REC-01',
    recycler_name: 'EcoTech E-Waste Recyclers',
    material: 'Computer Motherboards & RAM',
    amount: 10200,
    payment_status: 'Paid',
    payment_method: 'Direct Bank / UPI',
    transaction_date: 'Yesterday, 06:15 PM',
    receipt_ref: 'CPCB-RCP-8890',
  },
  {
    transaction_id: 'TXN-2026-979',
    lot_id: 'LOT-2026-103',
    collector_id: 'KC-DEL-2026-4892',
    recycler_id: 'REC-01',
    recycler_name: 'EcoTech E-Waste Recyclers',
    material: 'Stripped Copper Wire Scrap',
    amount: 6720,
    payment_status: 'Pending',
    payment_method: 'Direct Bank / UPI (On Handover)',
    transaction_date: 'Today, 09:15 AM',
    receipt_ref: 'CPCB-RCP-8921',
  },
  {
    transaction_id: 'TXN-2026-978',
    lot_id: 'LOT-2026-104',
    collector_id: 'KC-DEL-2026-4892',
    recycler_id: 'REC-02',
    recycler_name: 'GreenCircle Refurbishers Pvt Ltd',
    material: 'Mobile Phone & Tablet PCBs',
    amount: 7225,
    payment_status: 'Pending',
    payment_method: 'Direct Bank Transfer',
    transaction_date: 'Today, 11:30 AM',
    receipt_ref: 'CPCB-RCP-8940',
  },
  {
    transaction_id: 'TXN-2026-975',
    lot_id: 'LOT-2026-098',
    collector_id: 'KC-DEL-2026-4892',
    recycler_id: 'REC-02',
    recycler_name: 'GreenCircle Refurbishers Pvt Ltd',
    material: 'LCD / LED Monitors',
    amount: 3450,
    payment_status: 'Paid',
    payment_method: 'Direct Bank / UPI',
    transaction_date: '05 Sep 2026',
    receipt_ref: 'CPCB-RCP-8712',
  },
  {
    transaction_id: 'TXN-2026-970',
    lot_id: 'LOT-2026-095',
    collector_id: 'KC-DEL-2026-4892',
    recycler_id: 'REC-01',
    recycler_name: 'EcoTech E-Waste Recyclers',
    material: 'High-Grade Telecom Scrap',
    amount: 14200,
    payment_status: 'Paid',
    payment_method: 'Direct Bank / NEFT',
    transaction_date: '01 Sep 2026',
    receipt_ref: 'CPCB-RCP-8604',
  },
];
